# Generated by Django 3.0.4 on 2020-03-21 03:30

import access.fields
import access.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', access.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryTicket',
            fields=[
                ('uid', access.fields.SafeRandomField(default=access.fields.GenerateID(15, '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'), help_text='Server generated public unique ID', max_length=15, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
