#!/bin/sh


#curl --header "Content-Type: application/json" --request POST --data '{"matcher":"id", "matchee": "id", "longitude": "114.2999353", "latitude": "114.2999353", "matcher_meta": "meta information", "matchee_meta": "meta information"}' http://54.94.178.165/tracker/match/ -L -k
#curl --request POST http://54.94.178.165/auth/callback/
#curl --request POST http://54.94.178.165/auth/callback/
#curl --header "Content-Type: application/json" --request POST --data '{}' http://localhost/tracker/match/ -L -k

# curl --request POST http://127.0.0.1:8000/broadcast/subscribe/ --header "Content-Type: application/json" --data '{"endpoint": "asd", "device": "bcd"}'
curl --request POST http://54.94.178.165:8000/broadcast/subscribe/ --header "Content-Type: application/json" --data '{"endpoint": "arn:aws:sns:sa-east-1:494854379016:endpoint/APNS_SANDBOX/covidoff-ios/60446422-c641-35b4-824c-1d6d380e2669", "device": "bcd"}'

echo
