# Generated by Django 3.0.4 on 2020-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(default=None, help_text='Broadcast message title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Broadcast message text', max_length=4096),
        ),
    ]
