# Generated by Django 3.0.4 on 2020-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_auto_20200327_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='Subscription endpoint ARN', max_length=255)),
                ('device', models.TextField(help_text='Subscription device ID', max_length=255)),
            ],
        ),
    ]
