# Generated by Django 3.0.4 on 2020-03-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uid', models.CharField(help_text='Creation date', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcher_meta', models.CharField(help_text='Meta information associated with the matcher', max_length=2048)),
                ('matchee_meta', models.CharField(help_text='Meta information associated with the matchee', max_length=2048)),
                ('timestamp', models.DateTimeField(help_text='Timestamp event collected at the matcher device')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('matchee', models.ForeignKey(help_text='Matchee device', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_matchee', to='tracker.Device')),
                ('matcher', models.ForeignKey(help_text='Matcher device', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_matcher', to='tracker.Device')),
            ],
        ),
    ]
