# Generated by Django 3.0.4 on 2020-03-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='GPS coordinates for the match', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='GPS coordinates for the match', max_digits=9, null=True),
        ),
    ]
