# Generated by Django 3.0.4 on 2020-03-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200322_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='diagnosis',
        ),
    ]
