# Generated by Django 3.0.4 on 2020-03-28 17:54

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Model key', max_length=4)),
                ('description', models.CharField(help_text='Diagnosis description', max_length=256)),
                ('language', models.CharField(help_text='Language setting', max_length=8)),
            ],
            options={
                'unique_together': {('key', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uid', models.CharField(help_text='Device unique identifier', max_length=256, primary_key=True, serialize=False)),
                ('arn', models.TextField(help_text='Subscription endpoint ARN', max_length=256)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('diagnosis', models.ForeignKey(default=reports.models._default_diagnosis, help_text='COVID-19 Diagnosis', on_delete=django.db.models.deletion.PROTECT, to='reports.DiagnosticChoices')),
            ],
        ),
    ]
