# Generated by Django 3.0.4 on 2020-03-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS coordinates for the match', max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS coordinates for the match', max_digits=9, null=True)),
                ('matcher_meta', models.CharField(help_text='Meta information associated with the matcher', max_length=2048)),
                ('matchee_meta', models.CharField(help_text='Meta information associated with the matchee', max_length=2048)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('matchee', models.ForeignKey(help_text='Matchee device', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_matchee', to='reports.Device')),
                ('matcher', models.ForeignKey(help_text='Matcher device', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_matcher', to='reports.Device')),
            ],
        ),
    ]
